python -m app.product_hunter_runner
python -m app.hunter_import
python -m app.refresh_ebay_token
python -m app.health_check
python -m app.import_supplier_products
python -m app.update_shopify_existing
python -m app.product_hunter.service
python -m app.final_mvp.product_pipeline
python -m app.publish_ebay_from_imports
python -m app.daily_run
python -m app.pipeline_summary
python -m app.feeds.meta_shopify_feed
python -m app.feeds.google_merchant_feed
python -m app.auto_disable_skus
python -m app.sync_shopify_orders
python -m app.sync_shopify_orders
python -m app.sync_ebay_orders
python -m app.roi_report
python -m app.channel_health_report
python -m app.disable_candidates
python -m app.promotion_candidates
python -m app.promotion_actions
python -m app.sync_hunter_to_shopify
python -m app.promotion_plan
python -m app.pricing_experiments
python -m app.conversion_watch
python -m app.daily_decision_report
python -m app.seo_action_report
python -m app.seo_suggestions
python -m app.final_system_check
python -m app.supplier_purchase_queue
python -m app.cj_purchase_executor
python -m app.tracking_sync
python -m app.fulfillment_status_report
python -m app.push_tracking_to_channels
python -m app.collect_shopify_orders
python -m app.collect_woocommerce_orders
python -m app.collect_ebay_orders
python -m app.collect_incoming_orders
python -m app.market_arbitrage_engine
python -m app.arbitrage_decisions
python -m app.traffic_brain
python -m app.traffic_execution_plan
